DROP TABLE IF EXISTS Tags;
DROP TABLE IF EXISTS Nodes;

CREATE TABLE Nodes (
    id BIGINT NOT NULL PRIMARY KEY,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    _user VARCHAR(256) NOT NULL,
    uid BIGINT NOT NULL,
    version BIGINT NOT NULL,
    changeset BIGINT NOT NULL,
    _timestamp TIMESTAMP NOT NULL
);

CREATE TABLE Tags (
    node_id BIGINT NOT NULL REFERENCES Nodes(id),
    key VARCHAR(256) NOT NULL,
    value VARCHAR(256) NOT NULL
);